inherit_from: .rubocop_todo.yml

AllCops:
  StyleGuideCopsOnly: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FileName:
  Exclude: ['bin/*']

Style/SignalException:
  Enabled: false
