AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: true
  Exclude:
    - 'vendor/**/*'
    # Features syntax is a vendor file imported from Capybara. Ignore it.
    - 'lib/mediawiki_selenium/rspec/features.rb'
    # Ignore anything left around in `tmp`
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FileName:
  Exclude: ['bin/*']

Style/GuardClause:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true
